# Generated by Django 3.0.8 on 2020-07-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
