# Generated by Django 3.0.8 on 2020-07-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20200728_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
