# Generated by Django 3.0.8 on 2020-07-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20200728_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.Genres'),
        ),
    ]
