# Generated by Django 3.0.8 on 2020-08-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20200805_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Books.Authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Books.Genres'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Books.Publishers'),
        ),
    ]
